services:
  hello-dashboard:
    image: nginx:alpine
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`dashboard.aiclinicgenius.com`)
      - traefik.http.routers.dashboard.entrypoints=web,websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=mytlschallenge
      - traefik.http.services.dashboard.loadbalancer.server.port=80
    volumes:
      - ./build:/usr/share/nginx/html:ro
